# Generated by Django 3.2 on 2022-08-01 01:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('temps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCatalog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=254)),
                ('type', models.PositiveIntegerField(choices=[(1, 'CPU'), (2, 'HARDRIVE')], default=1)),
                ('alias', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceEquipment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('type_equipment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='temps.equipmentcatalog')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='temps',
            name='type_equipment',
        ),
        migrations.AddField(
            model_name='temps',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.AddField(
            model_name='temps',
            name='service_equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='temps.serviceequipment'),
        ),
    ]
