# Generated by Django 3.2 on 2022-08-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temps', '0002_auto_20220801_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceequipment',
            options={},
        ),
        migrations.AddField(
            model_name='serviceequipment',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='serviceequipment',
            index=models.Index(fields=['code'], name='temps_servi_code_5b6058_idx'),
        ),
    ]
