# Generated by Django 3.2 on 2022-08-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temps', '0003_auto_20220801_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentcatalog',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'CPU'), (2, 'HARDRIVE'), (3, 'RAM')], default=1),
        ),
    ]
