# Generated by Django 3.2 on 2022-08-06 16:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('temps', '0005_ramusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('alias', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['alias'], name='temps_serve_alias_332a15_idx'),
        ),
        migrations.AddField(
            model_name='serviceequipment',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='temps.server'),
        ),
    ]
